#!/usr/bin/env python3
"""codex_edit_gate.py — the bridge between Codex `apply_patch` and the shared `edit_gate.py`.

AUTO-GENERATED by `scripts/build_portable.py`. Hand edits here are lost on the next build.

Why it is needed: Claude Code sends `tool_input.file_path`, while Codex sends
`tool_input.command` holding the whole patch body (`*** Update File: <path>`). `edit_gate.py`
reads `file_path`, so running it straight under Codex yields an empty path — the gate exits 0
while guarding nothing at all, a silent failure.

Env: TDQ_LOG=0 turns the log off (it goes to stderr). Exit code and stdout come straight
from `edit_gate.py`.
"""
import datetime
import json
import os
import re
import subprocess
import sys

MAU_PATCH = re.compile(r"^\*\*\* (?:Update|Add|Delete) File: (.+)$", re.MULTILINE)


def log(message):
    if os.environ.get("TDQ_LOG", "1") != "0":
        stamp = datetime.datetime.now().astimezone().isoformat(timespec="seconds")
        print(f"[{stamp}] {message}", file=sys.stderr)


def tach_duong_dan_patch(than):
    """The FIRST path in the patch body, or an empty string. Never raises on odd input."""
    khop = MAU_PATCH.search(than or "")
    return khop.group(1).strip() if khop else ""


def main():
    raw = sys.stdin.read()
    try:
        payload = json.loads(raw) if raw.strip() else {}
    except ValueError:
        # A broken payload must not block the session: the gate is a reminder, not a security mechanism.
        log("codex_edit_gate: payload is not JSON, skipping")
        print("{}")
        return 0
    tool_input = payload.get("tool_input") or {}
    if not tool_input.get("file_path"):
        duong = tach_duong_dan_patch(tool_input.get("command"))
        if duong:
            tool_input["file_path"] = duong
            payload["tool_input"] = tool_input
            log(f"codex_edit_gate: apply_patch -> {duong}")
        else:
            log("codex_edit_gate: could not extract a path from the patch body")
    that = os.path.join(os.path.dirname(os.path.abspath(__file__)), "edit_gate.py")
    proc = subprocess.run([sys.executable, that], input=json.dumps(payload),
                          capture_output=True, text=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    return proc.returncode


if __name__ == "__main__":
    sys.exit(main())
